/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./components/ui/BaseDialog.vue')['default']
    ButtonLoading: typeof import('./components/ui/ButtonLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/ui/Toast.vue')['default']
    Wrapper: typeof import('./components/Wrapper.vue')['default']
  }
}
